Add missing getItemLabel (#5919)
# Why

UA grouped mobile beacons fails with `GroupedView.js:199 Uncaught TypeError: getItemLabel is not a function`.
This is a regression introduced with https://github.com/instana/ui-client/pull/5828 similar to https://github.com/instana/ui-client/pull/5851.


# What

Adding the missing functions.

# References

- https://instana.slack.com/archives/C31D9CDCM/p1617797052448500