build(deps): bump fork-ts-checker-webpack-plugin from 6.5.0 to 6.5.3
After TypeScript has been updated to 5.x in
ba983dd6206a048d00138fd25309259c84196746, fork-ts-checker-webpack-plugin
started to generate error messages:

TypeError: Cannot set property mark of #<Object> which has only a
getter

See also:
* https://instana.slack.com/archives/C5LCSUJGY/p1688066283396179
* https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/797#issuecomment-1455200765