Fixing broken span details (#5709)
# Why

Opening span details triggers the following error.

```
Unhandled error: Uncaught TypeError: span.get is not a function at webpack:///./packages/in-sdk/tracing/tracing.js?:44 TypeError: span.get is not a function
   at getType (tracing.js:44)
   at getTypeNameKeyContext (tracing.js:47)
   at getTypeLabel (tracing.js:83)
   at getTypeLabelSingular (tracing.js:87)
   at SpanDetails (SpanDetails.js:69)
   at renderWithHooks (react-dom.development.js:14803)
   at mountIndeterminateComponent (react-dom.development.js:17482)
   at beginWork (react-dom.development.js:18596)
   at HTMLUnknownElement.callCallback (react-dom.development.js:188)
   at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
```

# What

Using the right span object, i.e. `convertedSpan` instead of `span`.

# References

- https://instana.slack.com/archives/G5LCSUJGY/p1616055699022500