Push ui-client images to int-docker-backend-local repo (#11058) (#11076)
Co-authored-by: Will James <will.james@ibm.com>

# Why

The **backend** build is failing with the below error because it cannot find the **ui-client** package:

```
ERROR: delivery.instana.io/int-docker-backend-local/backend/ui-client:3.236.205-0: not found
```

This same issue occurred in `release-235` and was fixed by #11058, but that fix did not get picked up by the auto-updater for `release-236`.  

# What
Apply the same fix as #11058 so that the **ui-client** images are published to the `int-docker-backend-local/backend` repo path.

# Reference
- Failed **backend** `release-236` [build](https://dev-jenkins.instana.club/blue/organizations/jenkins/backend/detail/release-236/55/pipeline/)